name: Build EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow piexif google-generativeai
        
    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed --name ImageMetadataAutomator src/main.py
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ImageMetadataAutomator
        path: dist/ImageMetadataAutomator.exe